name: List services in GCP
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v1'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'https://iam.googleapis.com/projects/366974812144/locations/global/workloadIdentityPools/k8s-pool/attribute.repository/pedroaddias7/githubactions'
          service_account: 'git-k8s@gcloud-cd-playground-pdias.iam.gserviceaccount.com'
    
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}" --quiet
        gcloud services list --project gcloud-cd-playground-pdias